"""supervisor/llm_supervisor.py — OpenAI-powered judge."""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from openai import OpenAI

from supervisor.monitoring.session_tracker import (
    estimate_request_tokens,
    truncate_with_fallback,
    warn_if_exceeds_limit,
)
from supervisor.monitoring.token_estimator import should_truncate
from supervisor.protocols.protocol import Protocol
from supervisor.protocols.protocol_analyzer import ProtocolAnalysis, ProtocolAnalyzer
from supervisor.utils.file_ops import safe_read_text
from supervisor.utils.path_filters import DEFAULT_IGNORE_DIRS, DEFAULT_IGNORE_PREFIXES
from supervisor.utils.text_utils import strip_thinking_blocks
from supervisor.workspace.ignore_patterns import IgnoreMatcher

logger = logging.getLogger(__name__)


def _get_model_token_limit(model: str) -> int:
    """Get the maximum input token limit for a given model."""
    return 128_000


_TOKEN_LIMIT_ERROR_MARKERS = (
    "range of input length",
    "input length",
    "input token count",
    "maximum number of tokens",
    "maximum context length",
    "context length exceeded",
    "context_length_exceeded",
    "max tokens",
    "exceeds the maximum",
    "too many tokens",
    "token count exceeds",
    "prompt is too long",
    "request too large",
    "reduce the length",
)


def _is_token_limit_error(exc: Exception) -> bool:
    """Return True when the error indicates the prompt exceeded the model's token limit."""
    message = str(exc).lower()
    if any(marker in message for marker in _TOKEN_LIMIT_ERROR_MARKERS):
        return True
    body = getattr(exc, "body", None)
    if isinstance(body, dict):
        err = body.get("error") if isinstance(body.get("error"), dict) else body
        code = str(err.get("code", "")) if isinstance(err, dict) else ""
        status = str(err.get("status", "")) if isinstance(err, dict) else ""
        msg = str(err.get("message", "")).lower() if isinstance(err, dict) else ""
        if status == "INVALID_ARGUMENT" and any(
            marker in msg for marker in _TOKEN_LIMIT_ERROR_MARKERS
        ):
            return True
        if code in {"context_length_exceeded", "string_above_max_length"}:
            return True
    return False


def _check_completion_phrases(reply: str, phrases: list[str]) -> bool:
    """Check if any completion phrase appears positively in the reply."""
    reply_lower = reply.lower()

    # Negation patterns that should invalidate a match
    negation_prefixes = [
        r"not\s+", r"never\s+", r"failed\s+to\s+", r"unable\s+to\s+",
        r"did\s+not\s+", r"does\s+not\s+", r"don't\s+", r"doesn't\s+",
        r"won't\s+", r"cannot\s+", r"can't\s+",
    ]

    for phrase in phrases:
        # Build regex with word boundaries
        pattern = r"\b" + re.escape(phrase) + r"\b"

        # Find all matches with their positions
        for match in re.finditer(pattern, reply_lower):
            start = match.start()
            # Check ~50 chars before the match for negation
            prefix_context = reply_lower[max(0, start - 50):start]

            # If no negation pattern precedes this match, it's a valid positive signal
            if not any(re.search(neg, prefix_context) for neg in negation_prefixes):
                return True
    return False


# Markdown files generated by opencode that should be excluded
# when searching for external feedback files.
_OPENCODE_GENERATED_MD: set[str] = {
    "summary.md",
    "failure_report.md",
    "evolution_report.md",
}

_SKIP_DIRS = DEFAULT_IGNORE_DIRS | {".opencode", "opencode_supervisor.egg-info"}
_SKIP_DIR_PREFIXES = DEFAULT_IGNORE_PREFIXES


@dataclass
class ProtocolViolation:
    section: str
    description: str
    suggestion: str


@dataclass
class AlignmentResult:
    aligned: bool
    violations: list[ProtocolViolation] = field(default_factory=list)
    reinforcement_message: str = ""


_DONE_PHRASES = [
    "all targets met",
    "all targets are met",
    "targets achieved",
    "task complete",
    "task is complete",
    "objectives met",
    "protocol satisfied",
]


@dataclass
class SupervisorVerdict:
    raw: str
    all_targets_met: bool
    feedback: str


@dataclass
class StepContext:
    current_step: int = 0
    total_steps_estimate: int = 5
    phase: str = "unknown"
    completed_phases: list[str] = field(default_factory=list)


class LLMSupervisor:
    """Wraps an OpenAI chat client. Protocol is the system prompt;
    conversation history gives the supervisor persistent memory.
    """

    _INTERMEDIATE_STEP_MARKER = "_is_intermediate_step"

    def __init__(
        self,
        protocol: Protocol,
        workspace: Path,
        model: str,
        extra_system: str = "",
        read_external_feedback: bool = False,
        max_tokens: int = 128_000,
        max_protected_files_for_suggestions: int = 5,
        truncation_enabled: bool = True,
        max_history_turns: int = 40,
        compact_intermediate_steps: bool = False,
        model_backup: str | None = None,
    ):
        self._client = OpenAI()
        self._model = model
        self._model_backup = model_backup
        self._workspace = workspace
        self._system_base = protocol.as_system_prompt(workspace)
        self._system = self._system_base
        if extra_system:
            self._system += f"\n\n{extra_system}"
        self._protocol_target = protocol.target_section
        self._history: list[dict] = []
        self._read_external_feedback = read_external_feedback
        self._model_input_limit = _get_model_token_limit(model)
        self._max_tokens = min(max_tokens, self._model_input_limit)
        self._token_warnings: list[str] = []
        self._max_protected_files_for_suggestions = max_protected_files_for_suggestions
        self._truncation_enabled = truncation_enabled
        self._max_history_turns = max_history_turns
        self._compact_intermediate_steps = compact_intermediate_steps
        self._ignore_matcher = IgnoreMatcher(workspace)
        self._ignore_matcher.load_from_workspace(workspace)
        self._last_opencode_output: str | None = None

    def _get_model_limit_for_model(self, model: str) -> int:
        """Get token limit for a specific model (handles backup model)."""
        return _get_model_token_limit(model)

    @staticmethod
    def _extract_token_limit_from_error(exc: Exception) -> int | None:
        """Extract the numeric token limit from a provider error message, if present."""
        text = str(exc)
        body = getattr(exc, "body", None)
        if isinstance(body, dict):
            err = body.get("error") if isinstance(body.get("error"), dict) else body
            if isinstance(err, dict):
                text = f"{text} {err.get('message', '')}"
        match = re.search(r"(\d{4,7})", text)
        if not match:
            return None
        try:
            value = int(match.group(1))
        except ValueError:
            return None
        if 1024 <= value <= 10_000_000:
            return value
        return None

    def read_protected_files(self) -> dict[str, str]:
        """Read all protected files and return their content as a dict mapping path to content."""
        protected_contents: dict[str, str] = {}
        workspace = self._workspace.resolve()

        # Read .opencoderc if it exists at workspace root
        opencoderc = workspace / ".opencoderc"
        if opencoderc.is_file():
            try:
                rel = opencoderc.relative_to(workspace)
                protected_contents[str(rel)] = safe_read_text(opencoderc)
            except (OSError, UnicodeDecodeError):
                pass

        # Read .opencode file if it exists at workspace root (as a file)
        opencode_file = workspace / ".opencode"
        if opencode_file.is_file():
            try:
                rel = opencode_file.relative_to(workspace)
                protected_contents[str(rel)] = safe_read_text(opencode_file)
            except (OSError, UnicodeDecodeError):
                pass

        # Read all files in .opencode/ directory
        opencode_dir = workspace / ".opencode"
        if opencode_dir.is_dir():
            for dirpath, dirnames, filenames in os.walk(opencode_dir):
                dirnames[:] = [
                    d
                    for d in dirnames
                    if d not in _SKIP_DIRS
                    and not any(d.startswith(p) for p in _SKIP_DIR_PREFIXES)
                ]
                for fname in filenames:
                    if fname.endswith(".log"):
                        continue
                    fpath = Path(dirpath) / fname
                    try:
                        rel = fpath.relative_to(workspace)
                        protected_contents[str(rel)] = safe_read_text(fpath)
                    except (OSError, UnicodeDecodeError):
                        pass

        return protected_contents

    def _should_skip_file(self, path: str) -> bool:
        """Check if a file path matches any pattern in .opencodeignore.

        Args:
            path: The relative path of the file to check.

        Returns:
            True if the file should be skipped, False otherwise.
            Protected files (.opencoderc, .opencode/*) are never skipped.

        """
        protected_markers = (".opencoderc", ".opencode/")
        if any(
            path.startswith(pm) or path == pm.rstrip("/") for pm in protected_markers
        ):
            return False

        return self._ignore_matcher.matches(path)

    def _llm_select_files(self, file_meta: dict[str, int], top_k: int) -> list[str]:
        """Ask the LLM to pick the top-k most relevant files given path+size metadata.

        Args:
            file_meta: Mapping of relative path -> byte size for every candidate file.
            top_k: Maximum number of files to return.

        Returns:
            List of relative path strings chosen by the LLM (length <= top_k).
            Falls back to the first top_k sorted paths if the response cannot be parsed.

        """
        import json as _json

        if not file_meta:
            return []

        filtered_meta = {
            path: size
            for path, size in file_meta.items()
            if not self._should_skip_file(path)
        }

        if not filtered_meta:
            return []

        # Budget: each path can be up to ~100 chars (~25 tokens); add overhead for
        # JSON brackets, commas, and whitespace. Minimum 256 to be safe.
        response_budget = max(256, top_k * 50)

        # Ensure the prompt doesn't exceed max_tokens
        # The prompt template without listing is about 150 tokens
        available_tokens = max(1000, self._max_tokens - response_budget - 200)

        # Sort items to prioritize (maybe by size, or just alphabetical, we already sorted alphabetical)
        sorted_items = sorted(filtered_meta.items())

        # Build listing iteratively to fit within available tokens
        # Or we can just use estimate_tokens on the listing and truncate
        listing_lines = []
        for path, size in sorted_items:
            listing_lines.append(f"{path} ({size} bytes)")

        from supervisor.monitoring.session_tracker import SessionTracker

        listing = "\n".join(listing_lines)
        if SessionTracker.estimate_tokens(listing) > available_tokens:
            # We must truncate the listing
            listing = SessionTracker.truncate_prompt(
                listing, available_tokens, preserve_end_ratio=0.0,
            )

        from supervisor.prompts import FILE_SELECTION_PROMPT

        prompt = FILE_SELECTION_PROMPT.format(
            top_k=top_k,
            protocol_target=self._protocol_target,
            total_candidates=len(filtered_meta),
            listing=listing,
        )

        try:
            kwargs = {
                "model": self._model,
                "messages": [{"role": "user", "content": prompt}],
            }
            if self._model.startswith(("o1", "o3")):
                kwargs["max_completion_tokens"] = response_budget
            else:
                kwargs["max_tokens"] = response_budget
                kwargs["temperature"] = 0.0

            self._log_prompt("LLM Select Files", kwargs["messages"])

            response = self._client.chat.completions.create(**kwargs)
            raw = (response.choices[0].message.content or "").strip()

            # Extract list of strings using regex if json fails or as an alternative
            selected = []
            try:
                match = re.search(r"\[.*\]", raw, re.DOTALL)
                if match:
                    selected = _json.loads(match.group(0))
                else:
                    selected = _json.loads(raw)
                if not isinstance(selected, list):
                    selected = []
            except Exception:
                # Fallback to regex extraction of string literals
                matches = re.findall(r'["\']([^"\']+)["\']', raw)
                selected = [m for m in matches if m]

            if not selected:
                raise ValueError("Could not extract any paths from LLM response")

            # Keep only paths that actually exist in filtered_meta
            real_paths = []
            for p in selected:
                p_str = str(p).strip()
                if not p_str:
                    continue

                if p_str in filtered_meta:
                    if p_str not in real_paths:
                        real_paths.append(p_str)
                    continue

                # try suffix/prefix match
                p_norm = p_str.replace("\\", "/").strip("/")
                best_match = None
                for candidate in filtered_meta:
                    c_norm = candidate.replace("\\", "/").strip("/")
                    if (
                        c_norm.endswith("/" + p_norm)
                        or p_norm.endswith("/" + c_norm)
                        or c_norm == p_norm
                    ):
                        best_match = candidate
                        break

                # try basename match if suffix match fails
                if not best_match:
                    p_name = p_norm.split("/")[-1]
                    for candidate in filtered_meta:
                        c_name = candidate.replace("\\", "/").strip("/").split("/")[-1]
                        if c_name == p_name:
                            best_match = candidate
                            break

                if best_match and best_match not in real_paths:
                    real_paths.append(best_match)

            return real_paths[:top_k]
        except Exception as exc:
            logger.warning(
                "LLM file selection failed (%s); falling back to first %d files.",
                exc,
                top_k,
            )
            return sorted(filtered_meta)[:top_k]

    def _read_protected_files_for_suggestions(self) -> tuple[dict[str, str], list[str]]:
        """Walk the full workspace, let the LLM choose the top-k most relevant files,
        then return their contents and the list of chosen paths.

        Dot-prefixed directories (.git, .opencode, etc.) and generated markdown
        files are excluded from consideration. The number of files returned is
        capped at self._max_protected_files_for_suggestions.
        """
        workspace = self._workspace.resolve()
        top_k = self._max_protected_files_for_suggestions

        # Collect candidate paths and their sizes — no content read yet.
        file_meta: dict[str, int] = {}
        try:
            for path in workspace.rglob("*"):
                if not path.is_file():
                    continue
                rel_parts = path.relative_to(workspace).parts
                # Skip anything inside a dot-prefixed directory.
                if any(part.startswith(".") for part in rel_parts):
                    continue
                # Skip files generated by opencode/supervisor.
                if path.name in _OPENCODE_GENERATED_MD:
                    continue
                try:
                    file_meta[str(path.relative_to(workspace))] = path.stat().st_size
                except OSError:
                    pass
        except OSError as exc:
            logger.warning("Could not walk workspace for file selection: %s", exc)

        if not file_meta:
            return {}, []

        # Ask the LLM which files are most worth reading.
        chosen_paths = self._llm_select_files(file_meta, top_k)

        # Read only the chosen files.
        result: dict[str, str] = {}
        for rel_str in chosen_paths:
            try:
                result[rel_str] = safe_read_text(workspace / rel_str)
            except (OSError, UnicodeDecodeError) as exc:
                logger.warning("Could not read selected file %s: %s", rel_str, exc)

        return result, chosen_paths

    def _find_feedback_file(self) -> Path | None:
        """Find the latest modified markdown file not generated by opencode.

        Falls back to the latest modified file (any extension) if no such
        markdown file exists in the workspace.
        """
        workspace = self._workspace.resolve()
        if not workspace.is_dir():
            return None

        latest_md: Path | None = None
        latest_md_mtime: float = -1.0
        latest_any: Path | None = None
        latest_any_mtime: float = -1.0

        for dirpath, dirnames, filenames in os.walk(workspace):
            dirnames[:] = [
                d
                for d in dirnames
                if d not in _SKIP_DIRS
                and not any(d.startswith(p) for p in _SKIP_DIR_PREFIXES)
            ]
            for fname in filenames:
                fpath = Path(dirpath) / fname
                try:
                    mtime = fpath.stat().st_mtime
                except OSError:
                    continue

                if mtime > latest_any_mtime:
                    latest_any_mtime = mtime
                    latest_any = fpath

                if (
                    fpath.suffix.lower() == ".md"
                    and fname not in _OPENCODE_GENERATED_MD
                ):
                    if mtime > latest_md_mtime:
                        latest_md_mtime = mtime
                        latest_md = fpath

        if latest_md is not None:
            logger.info(
                "Using external feedback file: %s",
                latest_md.relative_to(workspace),
            )
            return latest_md

        if latest_any is not None:
            logger.info(
                "No non-generated .md found; falling back to latest file: %s",
                latest_any.relative_to(workspace),
            )
            return latest_any

        return None

    def _read_feedback_content(self, feedback_file: Path) -> str:
        """Read the content of a feedback file, returning empty string on failure."""
        try:
            content = safe_read_text(feedback_file)
            logger.info(
                "Read %d chars from feedback file: %s",
                len(content),
                feedback_file.relative_to(self._workspace.resolve()),
            )
            return content
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("Failed to read feedback file %s: %s", feedback_file, exc)
            return ""

    def _get_evaluation_context(self) -> tuple[str, str]:
        protected_files = self.read_protected_files()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        feedback_context = ""
        if self._read_external_feedback:
            feedback_file = self._find_feedback_file()
            if feedback_file is not None:
                fb_content = self._read_feedback_content(feedback_file)
                if fb_content:
                    feedback_context = (
                        f"\n\n## External Feedback (from {feedback_file.name})\n"
                        f"{fb_content}\n"
                        "Use this external feedback as the primary evaluation input.\n\n"
                    )
        return protected_context, feedback_context

    def _build_experience_context(self) -> str:
        """Read experience.md from workspace and format for prompt injection.

        Returns empty string if the file is missing or unreadable.
        Failures are logged but never raised.
        """
        try:
            from supervisor.monitoring.session_tracker import SessionTracker
            from supervisor.utils.experience_tracker import read_experience_capped

            experience_text = read_experience_capped(self._workspace, max_chars=10000)
            if not experience_text.strip():
                return ""

            # Ensure experience does not exceed a reasonable budget (e.g., 10% of max_tokens)
            budget = int(self._max_tokens * 0.1)
            if SessionTracker.estimate_tokens(experience_text) > budget:
                experience_text = SessionTracker.truncate_prompt(
                    experience_text, budget, preserve_end_ratio=0.0,
                )

            return (
                f"--- Previous Experience ---\n{experience_text}\n--- end ---\n\n"
            )
        except Exception as exc:
            logger.warning("Failed to build experience context: %s", exc)
        return ""

    def judge(self, opencode_output: str) -> SupervisorVerdict:
        from supervisor.prompts.templates import (
            build_context_blocks,
            build_judge_prompt,
        )

        experience_context = self._build_experience_context()
        protected_context, feedback_context = self._get_evaluation_context()

        context_blocks = build_context_blocks(feedback_context, protected_context, experience_context)
        msg = build_judge_prompt(opencode_output, context_blocks=context_blocks)
        history_msg = build_judge_prompt(opencode_output, context_blocks="")
        return self._chat(msg, history_content=history_msg)

    def judge_with_step_context(
        self,
        opencode_output: str,
        step_context: StepContext,
    ) -> SupervisorVerdict:
        from supervisor.prompts import JUDGE_STEP_PROMPT
        protected_context, feedback_context = self._get_evaluation_context()
        phases_str = (
            ", ".join(step_context.completed_phases)
            if step_context.completed_phases
            else "none"
        )
        experience_context = self._build_experience_context()

        # Token-aware step context omission
        omit_sc = self._should_omit_step_context(
            opencode_output, experience_context, feedback_context, protected_context,
        )

        msg = JUDGE_STEP_PROMPT.format(
            current_step=step_context.current_step,
            total_steps=step_context.total_steps_estimate,
            phase=step_context.phase,
            completed_phases=phases_str,
            experience_context=experience_context,
            feedback_context=feedback_context,
            protected_context=protected_context,
            opencode_output=opencode_output,
        )
        history_msg = JUDGE_STEP_PROMPT.format(
            current_step=0 if omit_sc else step_context.current_step,
            total_steps=0 if omit_sc else step_context.total_steps_estimate,
            phase="" if omit_sc else step_context.phase,
            completed_phases="" if omit_sc else phases_str,
            experience_context="",
            feedback_context="",
            protected_context="",
            opencode_output=opencode_output,
        )
        return self._chat(msg, history_content=history_msg)

    def judge_plan(
        self,
        opencode_output: str,
        plan_round: int,
        total_plan_rounds: int,
        step_context: StepContext | None = None,
    ) -> SupervisorVerdict:
        """Evaluate opencode's plan output during the plan phase.

        Unlike judge/judge_with_step_context this method explicitly tells the
        supervisor that opencode is still *planning* — no code changes have been
        made yet.  The verdict's ``feedback`` is used as the next prompt sent to
        opencode; ``all_targets_met`` is intentionally never set True here so the
        plan phase always runs for the configured number of rounds before handing
        off to build mode.

        Args:
            opencode_output: The raw text produced by opencode in this round.
            plan_round: 1-based index of the current plan round.
            total_plan_rounds: Total number of plan rounds configured.
            step_context: Optional step/phase context from the step detector.

        Returns:
            SupervisorVerdict with feedback to send back to opencode.

        """
        from supervisor.prompts.templates import (
            build_context_blocks,
            build_plan_judge_prompt,
            build_step_context,
        )

        protected_context, feedback_context = self._get_evaluation_context()

        context_info = ""
        if step_context is not None:
            phases_str = (
                ", ".join(step_context.completed_phases)
                if step_context.completed_phases
                else "none"
            )
            context_info = build_step_context(
                step_context.current_step,
                step_context.total_steps_estimate,
                step_context.phase,
                phases_str,
            ) + "\n"

        experience_context = self._build_experience_context()
        context_blocks = build_context_blocks(feedback_context, protected_context, experience_context)

        msg = build_plan_judge_prompt(
            opencode_output=opencode_output,
            plan_round=plan_round,
            total_plan_rounds=total_plan_rounds,
            step_context=context_info,
            context_blocks=context_blocks,
        )
        history_msg = build_plan_judge_prompt(
            opencode_output=opencode_output,
            plan_round=plan_round,
            total_plan_rounds=total_plan_rounds,
            step_context=context_info,
            context_blocks="",
        )

        verdict = self._chat(msg, history_content=history_msg)

        # Plan mode never terminates early — override all_targets_met so the
        # caller (SupervisorLoop._run_plan_mode) controls the round count.
        return SupervisorVerdict(
            raw=verdict.raw,
            all_targets_met=False,
            feedback=verdict.feedback,
        )

    def ask_for_compaction_instructions(self) -> SupervisorVerdict:
        from supervisor.prompts import COMPACTION_INSTRUCTIONS_PROMPT

        return self._chat(COMPACTION_INSTRUCTIONS_PROMPT)

    def ask_for_deletion_permission(
        self,
        candidates: list[str],
        workspace: Path,
    ) -> SupervisorVerdict:
        if not candidates:
            return self.ask_for_compaction_instructions()

        file_list = "\n".join(f"  - {f}" for f in candidates)
        from supervisor.prompts import DELETION_PERMISSION_PROMPT

        msg = DELETION_PERMISSION_PROMPT.format(file_list=file_list)
        return self._chat(msg)

    def report_final_status(
        self,
        reason: str,
        opencode_output: str,
    ) -> str:
        msg = (
            f"Run ending. Reason: {reason}\n\n"
            "Write a final report:\n"
            "1. What has been completed.\n"
            "2. Last known bug / blocker.\n"
            "3. Remaining undone tasks.\n\n"
            f"Latest opencode output:\n{opencode_output}"
        )
        return self._chat(msg).raw

    def generate_suggestions(
        self,
        opencode_output: str,
        current_summary: str = "",
        step_context: StepContext | None = None,
    ) -> tuple[str, list[str]]:
        from supervisor.prompts.templates import (
            build_context_blocks,
            build_step_context,
        )

        protected_files, chosen_paths = self._read_protected_files_for_suggestions()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        step_context_block = ""
        if step_context:
            phases_str = (
                ", ".join(step_context.completed_phases)
                if step_context.completed_phases
                else "none"
            )
            step_context_block = build_step_context(
                step_context.current_step,
                step_context.total_steps_estimate,
                step_context.phase,
                phases_str,
            )

        summary_context = (
            f"\n\nCurrent implementation summary:\n{current_summary}"
            if current_summary
            else ""
        )

        PREAMBLE = (
            "Based on the opencode output below and the current implementation status,\n"
            "generate actionable suggestions for improving the code or approach.\n"
            "Focus on:\n"
            "1. Code quality improvements\n"
            "2. Potential bugs or edge cases\n"
            "3. Performance optimizations\n"
            "4. Better patterns or practices\n"
            "5. Missing tests or error handling\n\n"
        )
        POSTSCRIPT = (
            "Output ONLY the suggestions in a clear, actionable format. "
            "If no suggestions are needed, output 'No suggestions at this time.'"
        )

        context_blocks = build_context_blocks("", "", protected_context)
        msg = (
            f"{PREAMBLE}"
            f"--- Step Context ---\n{step_context_block}"
            f"{context_blocks}"
            f"--- opencode output ---\n"
            f"{opencode_output}\n--- end ---{summary_context}\n\n"
            f"{POSTSCRIPT}"
        )

        history_step_context = build_step_context(0, 0, "unknown", "none") if step_context else ""
        history_msg = (
            f"{PREAMBLE}"
            f"--- Step Context ---\n{history_step_context}"
            f"--- opencode output ---\n"
            f"{opencode_output}\n--- end ---{summary_context}\n\n"
        )

        return self._chat(msg, history_content=history_msg).raw, chosen_paths

    def analyze_protocol(
        self,
        protocol: Protocol,
        use_llm: bool = False,
    ) -> ProtocolAnalysis:
        analyzer = ProtocolAnalyzer()
        analysis = analyzer.analyze(protocol)

        if use_llm:
            msg = (
                "Analyze the following protocol for an autonomous coding agent. "
                "Evaluate its quality in terms of clarity, testability, and completeness. "
                "Identify any vague targets, missing restrictions, or unclear inputs. "
                "Provide specific, actionable suggestions for improvement.\n\n"
                f"## INPUT\n{protocol.input_section}\n\n"
                f"## TARGET\n{protocol.target_section}\n\n"
                f"## RESTRICTIONS\n{protocol.restrictions_section}\n\n"
                "Rate each section (INPUT, TARGET, RESTRICTIONS) on clarity, "
                "testability, and completeness (0-100). "
                "Then list specific issues and suggestions."
            )
            _ = self._chat(msg, is_intermediate=True)
            # The LLM feedback is stored in history for context enrichment

        return analysis

    def verify_protocol_alignment(
        self,
        opencode_output: str,
        protocol: Protocol,
    ) -> AlignmentResult:
        violations: list[ProtocolViolation] = []
        output_lower = opencode_output.lower()

        restriction_patterns = [
            (
                r"(do not delete|don't delete|never delete|avoid deleting)",
                "Attempting to delete code without permission",
                "Do not delete files unless explicitly instructed in the TARGET section.",
            ),
            (
                r"(rm\s+-rf|del\s+/[sqf]|\$\(\{|sudo\s+)",
                "Suspicious destructive command detected",
                "Destructive commands require explicit permission. Only proceed if the TARGET explicitly requires it.",
            ),
            (
                r"(\.\.\/|\.\.\\|\.\.\%|\.\.\.)",
                "Path traversal attempt detected",
                "All file operations must stay within the workspace directory. Do not access parent directories.",
            ),
            (
                r"(git\s+reset|git\s+rebase|git\s+push\s+--force|git\s+push\s+-f)",
                "Destructive git operation detected",
                "Do not perform destructive git operations (reset, rebase, force push) without explicit permission.",
            ),
            (
                r"(chmod\s+777|chmod\s+000|\$\(whoami\)|eval\s+\$\{)",
                "Risky shell operation detected",
                "Avoid risky operations involving permissions, command substitution in eval, or dynamic code execution.",
            ),
        ]

        for pattern, description, suggestion in restriction_patterns:
            if re.search(pattern, output_lower):
                violations.append(
                    ProtocolViolation(
                        section="RESTRICTIONS",
                        description=description,
                        suggestion=suggestion,
                    ),
                )

        if protocol.target_section:
            target_keywords = self._extract_keywords(protocol.target_section)
            found_keywords = sum(
                1 for kw in target_keywords if kw.lower() in output_lower
            )
            if target_keywords and found_keywords == 0:
                violations.append(
                    ProtocolViolation(
                        section="TARGET",
                        description="No evidence of target-related activity in output",
                        suggestion=f"Your output should address these target keywords: {', '.join(target_keywords[:5])}",
                    ),
                )

        if protocol.restrictions_section:
            restriction_keywords = self._extract_keywords(protocol.restrictions_section)
            for kw in restriction_keywords:
                if kw.lower() in output_lower and any(
                    word in output_lower
                    for word in ["ignore", "skip", "bypass", "violate"]
                ):
                    violations.append(
                        ProtocolViolation(
                            section="RESTRICTIONS",
                            description=f"Potential attempt to ignore restriction keyword: {kw}",
                            suggestion="You must comply with all restrictions listed in the protocol.",
                        ),
                    )
                    break

        aligned = len(violations) == 0
        reinforcement_message = (
            self._generate_reinforcement_message(violations) if violations else ""
        )

        return AlignmentResult(
            aligned=aligned,
            violations=violations,
            reinforcement_message=reinforcement_message,
        )

    def _extract_keywords(self, text: str) -> list[str]:
        words = re.findall(r"\b[a-zA-Z]{4,}\b", text)
        stopwords = {
            "that",
            "this",
            "with",
            "from",
            "have",
            "will",
            "been",
            "were",
            "they",
            "their",
            "what",
            "when",
            "your",
            "must",
            "only",
            "also",
            "into",
            "than",
            "then",
            "should",
            "could",
            "would",
            "which",
            "about",
            "after",
            "before",
            "being",
        }
        return [w for w in words if w.lower() not in stopwords][:10]

    def _generate_reinforcement_message(
        self,
        violations: list[ProtocolViolation],
    ) -> str:
        if not violations:
            return ""

        violations_text = ""
        for i, v in enumerate(violations, 1):
            violations_text += f"{i}. [{v.section}] {v.description}\n"
            violations_text += f"   Correction: {v.suggestion}\n\n"

        from supervisor.prompts import PROTOCOL_VIOLATION_TEMPLATE

        return PROTOCOL_VIOLATION_TEMPLATE.format(violations=violations_text)

    # ------------------------------------------------------------------ #

    def get_token_warnings(self) -> list[str]:
        """Return collected token warning messages."""
        return list(self._token_warnings)

    def clear_token_warnings(self) -> None:
        """Clear token warning messages."""
        self._token_warnings.clear()

    def should_record_turn(self, content: str, role: str = "user") -> bool:
        """Determine whether a turn should be added to history.

        When compact_intermediate_steps is enabled, this method filters out
        intermediate steps from opencode output while keeping final outputs
        and conclusions.

        Args:
            content: The message content
            role: The role of the message ('user' or 'assistant')

        Returns:
            True if the turn should be recorded, False otherwise

        """
        if not self._compact_intermediate_steps:
            return True

        if role != "user":
            return True

        content_lower = content.lower()

        intermediate_indicators = [
            "step ",
            "planning",
            "analyzing",
            "considering",
            "let me",
            "i'll need to",
            "creating",
            "writing",
            "modifying",
            "running test",
            "running tests",
            "test result",
            "progress:",
            "phase:",
            "moving to",
            "now ",
            "next ",
        ]

        final_indicators = [
            "all targets met",
            "all targets are met",
            "targets achieved",
            "task complete",
            "task is complete",
            "objectives met",
            "protocol satisfied",
            "feedback:",
            "recommendation:",
        ]

        is_intermediate = any(
            indicator in content_lower for indicator in intermediate_indicators
        )

        is_final = any(indicator in content_lower for indicator in final_indicators)

        return is_final or not is_intermediate

    def compact_history(self) -> None:
        """Remove intermediate steps from history while preserving essential conversation flow.

        This method keeps the first message (initial prompt) and the last N messages
        to preserve context, while removing intermediate steps in between.
        When compact_intermediate_steps is enabled, it identifies and removes
        intermediate step entries based on content analysis.
        """
        if not self._history or len(self._history) <= 2:
            return

        if not self._compact_intermediate_steps:
            return

        keep_count = min(self._max_history_turns, len(self._history) // 2)

        if keep_count < 1:
            return

        preserved: list[dict] = []

        if self._history:
            preserved.append(self._history[0])

        for msg in self._history[1:]:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if (
                role == "user" and self.should_record_turn(content, role)
            ) or role == "assistant":
                preserved.append(msg)

        if len(preserved) > keep_count + 1:
            if len(preserved) > 2:
                core = preserved[:2]
                tail = preserved[-keep_count:]
                self._history = core + tail
            else:
                self._history = preserved[-min(keep_count * 2, len(preserved)):]

    def estimate_current_tokens(self) -> int:
        """Estimate total tokens for current conversation state."""
        conv_parts = [m["content"] for m in self._history]
        conv_text = "\n".join(conv_parts)
        return estimate_request_tokens(
            self._system,
            conv_text,
            "",
        ).total

    def _log_prompt(self, title: str, messages: list[dict]) -> None:
        """Write the raw prompt messages to a .log file for debugging."""
        try:
            log_dir = self._workspace / ".opencode"
            log_dir.mkdir(parents=True, exist_ok=True)
            log_file = log_dir / "supervisor_prompts.log"

            with open(log_file, "a", encoding="utf-8") as f:
                f.write(f"\n{'=' * 80}\n")
                f.write(f"--- {title} ---\n")
                import datetime

                f.write(f"Timestamp: {datetime.datetime.now().isoformat()}\n")
                f.write(f"{'=' * 80}\n\n")
                for msg in messages:
                    role = msg.get("role", "unknown").upper()
                    content = msg.get("content", "")
                    f.write(f"[{role}]\n{content}\n\n{'-' * 40}\n\n")
        except Exception as e:
            logger.debug(f"Failed to log prompt: {e}")

    def _chat(
        self,
        user_content: str,
        is_intermediate: bool = False,
        history_content: str | None = None,
    ) -> SupervisorVerdict:
        should_record_user = (
            not is_intermediate
            or not self._compact_intermediate_steps
            or self.should_record_turn(user_content, "user")
        )
        # Deduplication: skip storing user message when it matches previous opencode output
        if should_record_user and self._last_opencode_output is not None:
            if user_content.strip() == self._last_opencode_output.strip():
                should_record_user = False

        record_content = (
            history_content if history_content is not None else user_content
        )

        conv_parts = []
        for msg in self._history:
            if msg.get("content"):
                conv_parts.append(msg["content"])
        conv_text = "\n".join(conv_parts)

        estimate = estimate_request_tokens(
            self._system,
            conv_text,
            user_content,
        )

        warning_msgs = warn_if_exceeds_limit(estimate, self._max_tokens)
        for msg in warning_msgs:
            self._token_warnings.append(msg)

        if should_truncate(estimate, self._max_tokens):
            logger.warning(
                "--- FULL PROMPT EXCEEDING MAX TOKENS ---\n"
                "SYSTEM:\n%s\n"
                "HISTORY:\n%s\n"
                "USER:\n%s\n"
                "----------------------------------------",
                self._system,
                conv_text,
                user_content,
            )

        if self._truncation_enabled and should_truncate(estimate, self._max_tokens):
            original_total = estimate.total
            user_content = self._fit_request_to_budget(user_content)
            new_estimate = estimate_request_tokens(
                self._system,
                "\n".join(m["content"] for m in self._history if m.get("content")),
                user_content,
            )
            trunc_warning = (
                f"Prompt truncated to fit within token limit. "
                f"Original: {original_total} tokens, New: {new_estimate.total} tokens, "
                f"Max available: {int(self._max_tokens * (1.0 - 0.25))} tokens"
            )
            logger.warning(trunc_warning)
            self._token_warnings.append(trunc_warning)

        messages = [{"role": "system", "content": self._system}]
        messages.extend(self._history)
        messages.append({"role": "user", "content": user_content})

        self._log_prompt("Supervisor Chat", messages)

        return self._chat_with_retry(messages, record_content, should_record_user)

    def _chat_with_retry(
        self,
        messages: list[dict],
        record_content: str,
        should_record_user: bool,
    ) -> SupervisorVerdict:
        import time

        from openai import (
            APIConnectionError,
            APIError,
            APITimeoutError,
            BadRequestError,
            InternalServerError,
            OpenAIError,
            RateLimitError,
        )

        max_retries = 5
        empty_choices_retries = 0
        max_empty_choices_retries = 3
        attempt = 0
        transient_attempt = 0
        max_transient_retries = 4
        working_messages = list(messages)
        using_backup = False
        token_limit_retry = 0
        max_token_limit_retries = 3

        while attempt <= max_retries:
            current_model = self._model_backup if using_backup else self._model
            try:
                response = self._client.chat.completions.create(
                    model=current_model,
                    messages=working_messages,
                )
                if not response.choices:
                    if empty_choices_retries >= max_empty_choices_retries:
                        raise OpenAIError("LLM response returned no choices after %d retries" % max_empty_choices_retries)
                    wait = 15 * (2 ** empty_choices_retries)
                    logger.warning(
                        "LLM response returned no choices, retry %d/%d after %ds",
                        empty_choices_retries + 1,
                        max_empty_choices_retries,
                        wait,
                    )
                    time.sleep(wait)
                    empty_choices_retries += 1
                    continue
                empty_choices_retries = 0
                reply = strip_thinking_blocks(response.choices[0].message.content or "")
                break
            except (RateLimitError, APIConnectionError, APITimeoutError) as exc:
                if transient_attempt >= max_transient_retries:
                    logger.error(
                        "Transient API error after %d retries, giving up: %s",
                        max_transient_retries,
                        exc,
                    )
                    raise
                wait = min(60, 5 * (2 ** transient_attempt))
                logger.warning(
                    "Transient API error %s (attempt %d/%d), retrying after %ds",
                    type(exc).__name__,
                    transient_attempt + 1,
                    max_transient_retries,
                    wait,
                )
                time.sleep(wait)
                transient_attempt += 1
                continue
            except BadRequestError as exc:
                if _is_token_limit_error(exc):
                    if token_limit_retry >= max_token_limit_retries:
                        logger.error(
                            "BadRequestError: input length exceeds model limit after %d retries",
                            max_token_limit_retries,
                        )
                        raise
                    current_limit = self._extract_token_limit_from_error(exc) or self._get_model_limit_for_model(current_model)
                    old_count = len(working_messages)
                    working_messages = self._truncate_messages_for_limit(working_messages, current_limit)
                    new_count = len(working_messages)
                    if new_count >= old_count:
                        working_messages = self._truncate_older_turns(working_messages)
                        new_count = len(working_messages)
                    token_limit_retry += 1
                    logger.warning(
                        "BadRequestError (input length) retry %d/%d: truncated messages from %d to %d for limit %d",
                        token_limit_retry,
                        max_token_limit_retries,
                        old_count,
                        new_count,
                        current_limit,
                    )
                    continue
                raise
            except (APIError, OpenAIError) as exc:
                if not using_backup and self._model_backup:
                    logger.warning(
                        "Primary model %s failed (%s), falling back to backup %s",
                        self._model,
                        exc,
                        self._model_backup,
                    )
                    using_backup = True
                    attempt = 0
                    continue
                if isinstance(exc, InternalServerError):
                    code = getattr(exc, "code", None) or getattr(
                        exc, "status_code", None,
                    )
                    body = str(exc)
                    if code != 511 and "max tokens" not in body.lower():
                        raise
                    if attempt >= max_retries:
                        logger.error(
                            "Prompt still exceeds token limit after %d truncation attempts",
                            max_retries,
                        )
                        raise

                    old_count = len(working_messages)
                    working_messages = self._truncate_older_turns(working_messages)
                    new_count = len(working_messages)
                    removed = old_count - new_count
                    attempt += 1
                    logger.warning(
                        "Token-limit retry %d/%d: removed %d older message(s), "
                        "now %d messages in request",
                        attempt,
                        max_retries,
                        removed,
                        new_count,
                    )
                else:
                    raise

        if should_record_user:
            self._history.append({"role": "user", "content": record_content})
        self._history.append({"role": "assistant", "content": reply})

        # Track last opencode output for deduplication in next turn
        self._extract_and_store_opencode_output(record_content, should_record_user)

        if len(self._history) > self._max_history_turns * 2:
            if self._compact_intermediate_steps:
                self.compact_history()
            else:
                self._history = self._history[:2] + self._history[4:]
        all_met = _check_completion_phrases(reply, _DONE_PHRASES)
        return SupervisorVerdict(raw=reply, all_targets_met=all_met, feedback=reply)

    def _should_omit_step_context(
        self,
        opencode_output: str,
        experience_context: str,
        feedback_context: str,
        protected_context: str,
    ) -> bool:
        """Decide whether to strip step-context from history to save tokens."""
        history_context = "".join([
            experience_context, feedback_context, protected_context,
            opencode_output,
        ])
        conv_text = "\n".join(m["content"] for m in self._history if m.get("content"))
        estimate = estimate_request_tokens(self._system, conv_text, history_context)
        threshold = int(self._max_tokens * 0.65)
        return estimate.total > threshold

    def _extract_and_store_opencode_output(self, content: str, should_record: bool) -> None:
        """Extract opencode output from record_content for deduplication tracking."""
        if not should_record:
            return
        for marker in ("--- opencode output ---", "--- opencode plan output ---"):
            start = content.find(marker)
            if start >= 0:
                output_start = start + len(marker)
                end_marker = content.find("\n--- end ---", output_start)
                if end_marker >= 0:
                    self._last_opencode_output = content[output_start:end_marker].strip()
                    return

    def update_system_prompt(self, new_preamble: str) -> None:
        """Update the extra_system preamble portion of the system prompt.

        This rebuilds the internal _system string by combining the protocol
        system prompt with the new preamble, without re-instantiating the class.
        """
        self._system = self._system_base
        if new_preamble:
            self._system += f"\n\n{new_preamble}"

    def _fit_request_to_budget(self, user_content: str) -> str:
        """Proactively shrink self._history and user_content to fit within token budget.

        Mutates self._history in place by dropping the oldest turns first, then
        truncates the tail of individual oversized messages, and finally falls back
        to truncating user_content. Returns the (possibly truncated) user_content.
        """
        from supervisor.monitoring.token_estimator import (
            estimate_tokens,
            truncate_prompt,
        )

        available = int(self._max_tokens * 0.75)
        system_tokens = estimate_tokens(self._system)
        budget = max(available - system_tokens, self._max_tokens // 8)

        def _msg_tokens(msg: dict) -> int:
            return estimate_tokens(msg.get("content", ""))

        history_tokens = sum(_msg_tokens(m) for m in self._history)
        user_tokens = estimate_tokens(user_content)

        if history_tokens + user_tokens <= budget:
            return user_content

        # Phase 1: drop oldest turns until we fit, preserving the very first turn
        # (initial task prompt) and the most recent exchanges.
        dropped_any = False
        while self._history and history_tokens + user_tokens > budget:
            # Always keep at least the last assistant/user pair to retain continuity.
            if len(self._history) <= 2:
                break
            # Drop the oldest message (index 0). If that drops a standalone user,
            # also drop its paired assistant response to keep alignment.
            removed = self._history.pop(0)
            history_tokens -= _msg_tokens(removed)
            dropped_any = True
            if (
                removed.get("role") == "user"
                and self._history
                and self._history[0].get("role") == "assistant"
            ):
                removed2 = self._history.pop(0)
                history_tokens -= _msg_tokens(removed2)

        # Phase 2: per-message truncation of any oversized remaining entry.
        per_msg_cap = max(budget // 4, 2_000)
        if history_tokens + user_tokens > budget:
            for msg in self._history:
                if _msg_tokens(msg) > per_msg_cap:
                    original = msg.get("content", "")
                    msg["content"] = truncate_prompt(original, per_msg_cap)
            history_tokens = sum(_msg_tokens(m) for m in self._history)

        # Phase 3: truncate user_content if still over budget.
        if history_tokens + user_tokens > budget:
            remaining_for_user = max(budget - history_tokens, budget // 4)
            user_content = truncate_prompt(user_content, remaining_for_user)

        if dropped_any:
            logger.warning(
                "Proactively trimmed history to fit budget (%d tokens, %d messages left)",
                budget,
                len(self._history),
            )

        return user_content

    @staticmethod
    def _truncate_older_turns(messages: list[dict]) -> list[dict]:
        if len(messages) <= 2:
            return messages

        result = [messages[0]]
        remaining = messages[1:]

        skip = 0
        if remaining and remaining[0].get("role") == "user":
            skip = 1
            if len(remaining) > 1 and remaining[1].get("role") == "assistant":
                skip = 2
        elif remaining and remaining[0].get("role") == "assistant":
            skip = 1

        result.extend(remaining[skip:])
        return result

    def _truncate_messages_for_limit(self, messages: list[dict], model_limit: int) -> list[dict]:
        """Truncate messages to fit within a specific model's token limit.

        This method is more aggressive than _truncate_older_turns and handles
        BadRequestError cases by reducing content significantly.
        """
        from supervisor.monitoring.token_estimator import estimate_tokens

        if len(messages) <= 1:
            return messages

        result = [messages[0]]
        remaining = messages[1:]

        system_tokens = estimate_tokens(messages[0].get("content", ""))
        target_budget = int(model_limit * 0.75) - system_tokens

        if target_budget <= 0:
            logger.warning("System prompt exceeds 75% of model limit, returning minimal messages")
            if len(messages) > 1:
                last_user = None
                for msg in reversed(messages):
                    if msg.get("role") == "user":
                        last_user = msg
                        break
                if last_user:
                    truncated_content = truncate_with_fallback(
                        last_user.get("content", ""),
                        model_limit // 2,
                    )
                    return [messages[0], {"role": "user", "content": truncated_content}]
            return messages[:1]

        current_tokens = 0
        preserved = []

        for msg in reversed(remaining):
            msg_tokens = estimate_tokens(msg.get("content", ""))
            if current_tokens + msg_tokens <= target_budget:
                preserved.insert(0, msg)
                current_tokens += msg_tokens

        result.extend(preserved)
        return result
