"""supervisor/llm_supervisor.py — OpenAI-powered judge."""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from openai import OpenAI

from supervisor.protocols.protocol import Protocol
from supervisor.protocols.protocol_analyzer import ProtocolAnalyzer, ProtocolAnalysis
from supervisor.monitoring.token_estimator import (
    estimate_request_tokens,
    should_truncate,
    truncate_with_fallback,
    warn_if_exceeds_limit,
)

logger = logging.getLogger(__name__)

# Markdown files generated by opencode that should be excluded
# when searching for external feedback files.
_OPENCODE_GENERATED_MD: set[str] = {
    "summary.md",
    "failure_report.md",
    "evolution_report.md",
}

_SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".checkpoints",
    ".archive",
    ".opencode",
    ".mypy_cache",
    ".pytest_cache",
    "opencode_supervisor.egg-info",
}
_SKIP_DIR_PREFIXES = (".",)


@dataclass
class ProtocolViolation:
    section: str
    description: str
    suggestion: str


@dataclass
class AlignmentResult:
    aligned: bool
    violations: list[ProtocolViolation] = field(default_factory=list)
    reinforcement_message: str = ""


_DONE_PHRASES = [
    "all targets met",
    "all targets are met",
    "targets achieved",
    "task complete",
    "task is complete",
    "objectives met",
    "protocol satisfied",
]


@dataclass
class SupervisorVerdict:
    raw: str
    all_targets_met: bool
    feedback: str


@dataclass
class StepContext:
    current_step: int = 0
    total_steps_estimate: int = 5
    phase: str = "unknown"
    completed_phases: list[str] = field(default_factory=list)


class LLMSupervisor:
    """
    Wraps an OpenAI chat client. Protocol is the system prompt;
    conversation history gives the supervisor persistent memory.
    """

    _INTERMEDIATE_STEP_MARKER = "_is_intermediate_step"

    def __init__(
        self,
        protocol: Protocol,
        workspace: Path,
        model: str,
        extra_system: str = "",
        read_external_feedback: bool = False,
        max_tokens: int = 128_000,
        max_protected_files_for_suggestions: int = 5,
        truncation_enabled: bool = True,
        max_history_turns: int = 40,
        compact_intermediate_steps: bool = False,
    ):
        self._client = OpenAI()
        self._model = model
        self._workspace = workspace
        self._system = protocol.as_system_prompt(workspace)
        self._protocol_target = protocol.target_section
        self._history: list[dict] = []
        self._read_external_feedback = read_external_feedback
        self._max_tokens = max_tokens
        self._token_warnings: list[str] = []
        self._max_protected_files_for_suggestions = max_protected_files_for_suggestions
        self._truncation_enabled = truncation_enabled
        self._max_history_turns = max_history_turns
        self._compact_intermediate_steps = compact_intermediate_steps

    def read_protected_files(self) -> dict[str, str]:
        """Read all protected files and return their content as a dict mapping path to content."""
        protected_contents: dict[str, str] = {}
        workspace = self._workspace.resolve()

        # Read .opencoderc if it exists at workspace root
        opencoderc = workspace / ".opencoderc"
        if opencoderc.is_file():
            try:
                rel = opencoderc.relative_to(workspace)
                protected_contents[str(rel)] = opencoderc.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                pass

        # Read .opencode file if it exists at workspace root (as a file)
        opencode_file = workspace / ".opencode"
        if opencode_file.is_file():
            try:
                rel = opencode_file.relative_to(workspace)
                protected_contents[str(rel)] = opencode_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                pass

        # Read all files in .opencode/ directory
        opencode_dir = workspace / ".opencode"
        if opencode_dir.is_dir():
            for dirpath, _dirnames, filenames in os.walk(opencode_dir):
                for fname in filenames:
                    fpath = Path(dirpath) / fname
                    try:
                        rel = fpath.relative_to(workspace)
                        protected_contents[str(rel)] = fpath.read_text(encoding="utf-8")
                    except (OSError, UnicodeDecodeError):
                        pass

        return protected_contents

    def _llm_select_files(self, file_meta: dict[str, int], top_k: int) -> list[str]:
        """Ask the LLM to pick the top-k most relevant files given path+size metadata.

        Args:
            file_meta: Mapping of relative path -> byte size for every candidate file.
            top_k: Maximum number of files to return.

        Returns:
            List of relative path strings chosen by the LLM (length <= top_k).
            Falls back to the first top_k sorted paths if the response cannot be parsed.
        """
        import json as _json

        if not file_meta:
            return []

        # Budget: each path can be up to ~100 chars (~25 tokens); add overhead for
        # JSON brackets, commas, and whitespace. Minimum 256 to be safe.
        response_budget = max(256, top_k * 50)

        # Ensure the prompt doesn't exceed max_tokens
        # The prompt template without listing is about 150 tokens
        available_tokens = max(1000, self._max_tokens - response_budget - 200)
        
        # Sort items to prioritize (maybe by size, or just alphabetical, we already sorted alphabetical)
        sorted_items = sorted(file_meta.items())
        
        # Build listing iteratively to fit within available tokens
        # Or we can just use estimate_tokens on the listing and truncate
        listing_lines = []
        for path, size in sorted_items:
            listing_lines.append(f"{path} ({size} bytes)")
            
        listing = "\n".join(listing_lines)
        
        from supervisor.monitoring.token_estimator import estimate_tokens, truncate_prompt
        if estimate_tokens(listing) > available_tokens:
            # We must truncate the listing
            listing = truncate_prompt(listing, available_tokens, preserve_end_ratio=0.0)

        prompt = (
            f"You are selecting the {top_k} most relevant source files to read "
            f"before generating code-improvement suggestions.\n\n"
            f"## Protocol target\n{self._protocol_target}\n\n"
            f"## Candidate files ({len(file_meta)} total)\n{listing}\n\n"
            f"Return ONLY a JSON array of up to {top_k} file paths from the list above, "
            f"ordered by relevance (most relevant first). "
            f'Example: ["src/main.py", "tests/test_core.py"]\n'
            f"Do not include any explanation or markdown — just the JSON array."
        )

        try:
            kwargs = {
                "model": self._model,
                "messages": [{"role": "user", "content": prompt}],
            }
            if self._model.startswith(("o1", "o3")):
                kwargs["max_completion_tokens"] = response_budget
            else:
                kwargs["max_tokens"] = response_budget
                kwargs["temperature"] = 0.0

            response = self._client.chat.completions.create(**kwargs)
            raw = (response.choices[0].message.content or "").strip()
            
            # Extract list of strings using regex if json fails or as an alternative
            selected = []
            try:
                match = re.search(r'\[.*\]', raw, re.DOTALL)
                if match:
                    selected = _json.loads(match.group(0))
                else:
                    selected = _json.loads(raw)
                if not isinstance(selected, list):
                    selected = []
            except Exception:
                # Fallback to regex extraction of string literals
                matches = re.findall(r'["\']([^"\']+)["\']', raw)
                selected = [m for m in matches if m]
                
            if not selected:
                raise ValueError("Could not extract any paths from LLM response")
                
            # Keep only paths that actually exist in file_meta
            real_paths = []
            for p in selected:
                p_str = str(p).strip()
                if not p_str:
                    continue
                    
                if p_str in file_meta:
                    if p_str not in real_paths:
                        real_paths.append(p_str)
                    continue
                    
                # try suffix/prefix match
                p_norm = p_str.replace("\\", "/").strip("/")
                best_match = None
                for candidate in file_meta:
                    c_norm = candidate.replace("\\", "/").strip("/")
                    if c_norm.endswith("/" + p_norm) or p_norm.endswith("/" + c_norm) or c_norm == p_norm:
                        best_match = candidate
                        break
                
                # try basename match if suffix match fails
                if not best_match:
                    p_name = p_norm.split("/")[-1]
                    for candidate in file_meta:
                        c_name = candidate.replace("\\", "/").strip("/").split("/")[-1]
                        if c_name == p_name:
                            best_match = candidate
                            break
                            
                if best_match and best_match not in real_paths:
                    real_paths.append(best_match)

            return real_paths[:top_k]
        except Exception as exc:
            logger.warning(
                "LLM file selection failed (%s); falling back to first %d files.",
                exc,
                top_k,
            )
            return sorted(file_meta)[:top_k]

    def _read_protected_files_for_suggestions(self) -> dict[str, str]:
        """Walk the full workspace, let the LLM choose the top-k most relevant files,
        then return their contents.

        Dot-prefixed directories (.git, .opencode, etc.) and generated markdown
        files are excluded from consideration. The number of files returned is
        capped at self._max_protected_files_for_suggestions.
        """
        workspace = self._workspace.resolve()
        top_k = self._max_protected_files_for_suggestions

        # Collect candidate paths and their sizes — no content read yet.
        file_meta: dict[str, int] = {}
        try:
            for path in workspace.rglob("*"):
                if not path.is_file():
                    continue
                rel_parts = path.relative_to(workspace).parts
                # Skip anything inside a dot-prefixed directory.
                if any(part.startswith(".") for part in rel_parts):
                    continue
                # Skip files generated by opencode/supervisor.
                if path.name in _OPENCODE_GENERATED_MD:
                    continue
                try:
                    file_meta[str(path.relative_to(workspace))] = path.stat().st_size
                except OSError:
                    pass
        except OSError as exc:
            logger.warning("Could not walk workspace for file selection: %s", exc)

        if not file_meta:
            return {}

        # Ask the LLM which files are most worth reading.
        chosen_paths = self._llm_select_files(file_meta, top_k)

        # Read only the chosen files.
        result: dict[str, str] = {}
        for rel_str in chosen_paths:
            try:
                result[rel_str] = (workspace / rel_str).read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError) as exc:
                logger.warning("Could not read selected file %s: %s", rel_str, exc)

        return result

    def _find_feedback_file(self) -> Path | None:
        """Find the latest modified markdown file not generated by opencode.

        Falls back to the latest modified file (any extension) if no such
        markdown file exists in the workspace.
        """
        workspace = self._workspace.resolve()
        if not workspace.is_dir():
            return None

        latest_md: Path | None = None
        latest_md_mtime: float = -1.0
        latest_any: Path | None = None
        latest_any_mtime: float = -1.0

        for dirpath, dirnames, filenames in os.walk(workspace):
            dirnames[:] = [
                d
                for d in dirnames
                if d not in _SKIP_DIRS
                and not any(d.startswith(p) for p in _SKIP_DIR_PREFIXES)
            ]
            for fname in filenames:
                fpath = Path(dirpath) / fname
                try:
                    mtime = fpath.stat().st_mtime
                except OSError:
                    continue

                if mtime > latest_any_mtime:
                    latest_any_mtime = mtime
                    latest_any = fpath

                if (
                    fpath.suffix.lower() == ".md"
                    and fname not in _OPENCODE_GENERATED_MD
                ):
                    if mtime > latest_md_mtime:
                        latest_md_mtime = mtime
                        latest_md = fpath

        if latest_md is not None:
            logger.info(
                "Using external feedback file: %s", latest_md.relative_to(workspace)
            )
            return latest_md

        if latest_any is not None:
            logger.info(
                "No non-generated .md found; falling back to latest file: %s",
                latest_any.relative_to(workspace),
            )
            return latest_any

        return None

    def _read_feedback_content(self, feedback_file: Path) -> str:
        """Read the content of a feedback file, returning empty string on failure."""
        try:
            content = feedback_file.read_text(encoding="utf-8")
            logger.info(
                "Read %d chars from feedback file: %s",
                len(content),
                feedback_file.relative_to(self._workspace.resolve()),
            )
            return content
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("Failed to read feedback file %s: %s", feedback_file, exc)
            return ""

    def judge(self, opencode_output: str) -> SupervisorVerdict:
        protected_files = self.read_protected_files()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        feedback_context = ""
        if self._read_external_feedback:
            feedback_file = self._find_feedback_file()
            if feedback_file is not None:
                fb_content = self._read_feedback_content(feedback_file)
                if fb_content:
                    feedback_context = (
                        f"\n\n## External Feedback (from {feedback_file.name})\n"
                        f"{fb_content}\n"
                        "Use this external feedback as the primary evaluation input.\n\n"
                    )

        msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            f"{feedback_context}"
            f"{protected_context}"
            f"--- opencode output ---\n{opencode_output}\n--- end ---"
        )
        history_msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            f"--- opencode output ---\n{opencode_output}\n--- end ---"
        )
        return self._chat(msg, history_content=history_msg)

    def judge_with_step_context(
        self, opencode_output: str, step_context: StepContext
    ) -> SupervisorVerdict:
        protected_files = self.read_protected_files()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        feedback_context = ""
        if self._read_external_feedback:
            feedback_file = self._find_feedback_file()
            if feedback_file is not None:
                fb_content = self._read_feedback_content(feedback_file)
                if fb_content:
                    feedback_context = (
                        f"\n\n## External Feedback (from {feedback_file.name})\n"
                        f"{fb_content}\n"
                        "Use this external feedback as the primary evaluation input.\n\n"
                    )

        phases_str = (
            ", ".join(step_context.completed_phases)
            if step_context.completed_phases
            else "none"
        )
        msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            "--- Step Context ---\n"
            f"Current step: {step_context.current_step}/{step_context.total_steps_estimate}\n"
            f"Current phase: {step_context.phase}\n"
            f"Completed phases: {phases_str}\n\n"
            f"{feedback_context}"
            f"{protected_context}"
            "--- opencode output ---\n"
            f"{opencode_output}\n--- end ---\n\n"
            "Focus your feedback on the current phase and remaining work."
        )
        history_msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            "--- Step Context ---\n"
            f"Current step: {step_context.current_step}/{step_context.total_steps_estimate}\n"
            f"Current phase: {step_context.phase}\n"
            f"Completed phases: {phases_str}\n\n"
            "--- opencode output ---\n"
            f"{opencode_output}\n--- end ---\n\n"
            "Focus your feedback on the current phase and remaining work."
        )
        return self._chat(msg, history_content=history_msg)

    def ask_for_compaction_instructions(self) -> SupervisorVerdict:
        msg = (
            "The opencode agent's context window is nearly full. "
            "Generate instructions for it to:\n"
            "1. Keep only the latest version of every file.\n"
            "2. Retain any foundational/fallback code it may reference.\n"
            "3. Write summary.md to the workspace with: current status, "
            "key decisions, remaining tasks and future directions.\n"
            "Output ONLY the instruction text to send to opencode."
        )
        return self._chat(msg)

    def ask_for_deletion_permission(
        self, candidates: list[str], workspace: Path
    ) -> SupervisorVerdict:
        if not candidates:
            msg = (
                "The opencode agent's context window is nearly full. "
                "Generate instructions for it to:\n"
                "1. Keep only the latest version of every file.\n"
                "2. Retain any foundational/fallback code it may reference.\n"
                "3. Write summary.md to the workspace with: current status, "
                "key decisions, remaining tasks and future directions.\n"
                "Output ONLY the instruction text to send to opencode."
            )
            return self._chat(msg)

        file_list = "\n".join(f"  - {f}" for f in candidates)
        msg = (
            "The opencode agent's context window is nearly full. "
            "Before compacting the context, you MUST address the following cleanup:\n\n"
            "## DELETION PERMISSION\n\n"
            "The supervisor has identified the following files as outdated, unused, or safe to delete:\n\n"
            f"{file_list}\n\n"
            "You are granted permission to DELETE these files ONLY if:\n"
            "1. The file is confirmed outdated (e.g., backup files, old versions, temp files)\n"
            "2. The file is unused by any current code\n"
            "3. The file is not a core module or essential configuration\n\n"
            "Generate instructions for the agent to:\n"
            "1. Review the file list above and DELETE only the confirmed outdated/unused files\n"
            "2. Keep all core modules and essential files\n"
            "3. Keep only the latest version of every file\n"
            "4. Retain any foundational/fallback code it may reference\n"
            "5. Write summary.md to the workspace with: current status, "
            "key decisions, remaining tasks and future directions\n\n"
            "Output ONLY the instruction text to send to opencode, "
            "including explicit permission to delete the listed files."
        )
        return self._chat(msg)

    def report_final_status(
        self, reason: str, opencode_output: str, workspace: Path
    ) -> str:
        msg = (
            f"Run ending. Reason: {reason}\n\n"
            "Write a final report:\n"
            "1. What has been completed.\n"
            "2. Last known bug / blocker.\n"
            "3. Remaining undone tasks.\n\n"
            f"Latest opencode output:\n{opencode_output}"
        )
        return self._chat(msg).raw

    def generate_suggestions(
        self,
        opencode_output: str,
        current_summary: str = "",
        step_context: StepContext | None = None,
    ) -> str:
        protected_files = self._read_protected_files_for_suggestions()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        context_info = ""
        if step_context:
            phases_str = (
                ", ".join(step_context.completed_phases)
                if step_context.completed_phases
                else "none"
            )
            context_info = (
                f"Current step: {step_context.current_step}/{step_context.total_steps_estimate}\n"
                f"Current phase: {step_context.phase}\n"
                f"Completed phases: {phases_str}\n\n"
            )

        summary_context = (
            f"\n\nCurrent implementation summary:\n{current_summary}"
            if current_summary
            else ""
        )

        msg = (
            "Based on the opencode output below and the current implementation status,\n"
            "generate actionable suggestions for improving the code or approach.\n"
            "Focus on:\n"
            "1. Code quality improvements\n"
            "2. Potential bugs or edge cases\n"
            "3. Performance optimizations\n"
            "4. Better patterns or practices\n"
            "5. Missing tests or error handling\n\n"
            f"--- Step Context ---\n{context_info}"
            f"{protected_context}"
            f"--- opencode output ---\n{opencode_output}\n--- end ---{summary_context}\n\n"
            "Output ONLY the suggestions in a clear, actionable format. "
            "If no suggestions are needed, output 'No suggestions at this time.'"
        )
        history_msg = (
            "Based on the opencode output below and the current implementation status,\n"
            "generate actionable suggestions for improving the code or approach.\n"
            "Focus on:\n"
            "1. Code quality improvements\n"
            "2. Potential bugs or edge cases\n"
            "3. Performance optimizations\n"
            "4. Better patterns or practices\n"
            "5. Missing tests or error handling\n\n"
            f"--- Step Context ---\n{context_info}"
            f"--- opencode output ---\n{opencode_output}\n--- end ---{summary_context}\n\n"
            "Output ONLY the suggestions in a clear, actionable format. "
            "If no suggestions are needed, output 'No suggestions at this time.'"
        )
        return self._chat(msg, history_content=history_msg).raw

    def analyze_protocol(
        self,
        protocol: Protocol,
        use_llm: bool = False,
    ) -> ProtocolAnalysis:
        analyzer = ProtocolAnalyzer()
        analysis = analyzer.analyze(protocol)

        if use_llm:
            msg = (
                "Analyze the following protocol for an autonomous coding agent. "
                "Evaluate its quality in terms of clarity, testability, and completeness. "
                "Identify any vague targets, missing restrictions, or unclear inputs. "
                "Provide specific, actionable suggestions for improvement.\n\n"
                f"## INPUT\n{protocol.input_section}\n\n"
                f"## TARGET\n{protocol.target_section}\n\n"
                f"## RESTRICTIONS\n{protocol.restrictions_section}\n\n"
                "Rate each section (INPUT, TARGET, RESTRICTIONS) on clarity, "
                "testability, and completeness (0-100). "
                "Then list specific issues and suggestions."
            )
            llm_feedback = self._chat(msg, is_intermediate=True)
            # The LLM feedback is stored in history for context enrichment

        return analysis

    def verify_protocol_alignment(
        self,
        opencode_output: str,
        protocol: Protocol,
    ) -> AlignmentResult:
        violations: list[ProtocolViolation] = []
        output_lower = opencode_output.lower()

        restriction_patterns = [
            (
                r"(do not delete|don't delete|never delete|avoid deleting)",
                "Attempting to delete code without permission",
                "Do not delete files unless explicitly instructed in the TARGET section.",
            ),
            (
                r"(rm\s+-rf|del\s+/[sqf]|\$\(\{|sudo\s+)",
                "Suspicious destructive command detected",
                "Destructive commands require explicit permission. Only proceed if the TARGET explicitly requires it.",
            ),
            (
                r"(\.\.\/|\.\.\\|\.\.\%|\.\.\.)",
                "Path traversal attempt detected",
                "All file operations must stay within the workspace directory. Do not access parent directories.",
            ),
            (
                r"(git\s+reset|git\s+rebase|git\s+push\s+--force|git\s+push\s+-f)",
                "Destructive git operation detected",
                "Do not perform destructive git operations (reset, rebase, force push) without explicit permission.",
            ),
            (
                r"(chmod\s+777|chmod\s+000|\$\(whoami\)|eval\s+\$\{)",
                "Risky shell operation detected",
                "Avoid risky operations involving permissions, command substitution in eval, or dynamic code execution.",
            ),
        ]

        for pattern, description, suggestion in restriction_patterns:
            if re.search(pattern, output_lower):
                violations.append(
                    ProtocolViolation(
                        section="RESTRICTIONS",
                        description=description,
                        suggestion=suggestion,
                    )
                )

        if protocol.target_section:
            target_keywords = self._extract_keywords(protocol.target_section)
            found_keywords = sum(
                1 for kw in target_keywords if kw.lower() in output_lower
            )
            if target_keywords and found_keywords == 0:
                violations.append(
                    ProtocolViolation(
                        section="TARGET",
                        description="No evidence of target-related activity in output",
                        suggestion=f"Your output should address these target keywords: {', '.join(target_keywords[:5])}",
                    )
                )

        if protocol.restrictions_section:
            restriction_keywords = self._extract_keywords(protocol.restrictions_section)
            for kw in restriction_keywords:
                if kw.lower() in output_lower and any(
                    word in output_lower
                    for word in ["ignore", "skip", "bypass", "violate"]
                ):
                    violations.append(
                        ProtocolViolation(
                            section="RESTRICTIONS",
                            description=f"Potential attempt to ignore restriction keyword: {kw}",
                            suggestion="You must comply with all restrictions listed in the protocol.",
                        )
                    )
                    break

        aligned = len(violations) == 0
        reinforcement_message = (
            self._generate_reinforcement_message(violations) if violations else ""
        )

        return AlignmentResult(
            aligned=aligned,
            violations=violations,
            reinforcement_message=reinforcement_message,
        )

    def _extract_keywords(self, text: str) -> list[str]:
        words = re.findall(r"\b[a-zA-Z]{4,}\b", text)
        stopwords = {
            "that",
            "this",
            "with",
            "from",
            "have",
            "will",
            "been",
            "were",
            "they",
            "their",
            "what",
            "when",
            "your",
            "must",
            "only",
            "also",
            "into",
            "than",
            "then",
            "should",
            "could",
            "would",
            "which",
            "about",
            "after",
            "before",
            "being",
        }
        return [w for w in words if w.lower() not in stopwords][:10]

    def _generate_reinforcement_message(
        self, violations: list[ProtocolViolation]
    ) -> str:
        if not violations:
            return ""

        lines = [
            "\n--- PROTOCOL VIOLATION DETECTED ---\n",
            "The following protocol violations were detected in your output:\n",
        ]

        for i, v in enumerate(violations, 1):
            lines.append(f"{i}. [{v.section}] {v.description}")
            lines.append(f"   Correction: {v.suggestion}\n")

        lines.extend(
            [
                "Please review the protocol sections above and correct your approach.\n",
                "Reminder:\n",
                "  - INPUT section describes the task context you must understand\n",
                "  - TARGET section lists the objectives you must achieve\n",
                "  - RESTRICTIONS section defines boundaries you must not cross\n",
                "Re-read these sections and adjust your actions accordingly.\n",
                "--- END VIOLATION NOTICE ---\n",
            ]
        )

        return "".join(lines)

    # ------------------------------------------------------------------ #

    def get_token_warnings(self) -> list[str]:
        """Return collected token warning messages."""
        return list(self._token_warnings)

    def clear_token_warnings(self) -> None:
        """Clear token warning messages."""
        self._token_warnings.clear()

    def should_record_turn(self, content: str, role: str = "user") -> bool:
        """Determine whether a turn should be added to history.

        When compact_intermediate_steps is enabled, this method filters out
        intermediate steps from opencode output while keeping final outputs
        and conclusions.

        Args:
            content: The message content
            role: The role of the message ('user' or 'assistant')

        Returns:
            True if the turn should be recorded, False otherwise
        """
        if not self._compact_intermediate_steps:
            return True

        if role != "user":
            return True

        content_lower = content.lower()

        intermediate_indicators = [
            "step ",
            "planning",
            "analyzing",
            "considering",
            "let me",
            "i'll need to",
            "creating",
            "writing",
            "modifying",
            "running test",
            "running tests",
            "test result",
            "progress:",
            "phase:",
            "moving to",
            "now ",
            "next ",
        ]

        final_indicators = [
            "all targets met",
            "all targets are met",
            "targets achieved",
            "task complete",
            "task is complete",
            "objectives met",
            "protocol satisfied",
            "feedback:",
            "recommendation:",
        ]

        is_intermediate = any(
            indicator in content_lower for indicator in intermediate_indicators
        )

        is_final = any(indicator in content_lower for indicator in final_indicators)

        return is_final or not is_intermediate

    def compact_history(self) -> None:
        """Remove intermediate steps from history while preserving essential conversation flow.

        This method keeps the first message (initial prompt) and the last N messages
        to preserve context, while removing intermediate steps in between.
        When compact_intermediate_steps is enabled, it identifies and removes
        intermediate step entries based on content analysis.
        """
        if not self._history or len(self._history) <= 2:
            return

        if not self._compact_intermediate_steps:
            return

        keep_count = min(self._max_history_turns, len(self._history) // 2)

        if keep_count < 1:
            return

        preserved: list[dict] = []

        if self._history:
            preserved.append(self._history[0])

        for msg in self._history[1:]:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "user" and self.should_record_turn(content, role):
                preserved.append(msg)
            elif role == "assistant":
                preserved.append(msg)

        if len(preserved) > keep_count + 1:
            if len(preserved) > 2:
                core = preserved[:2]
                tail = preserved[-keep_count:]
                self._history = core + tail
            else:
                self._history = preserved[-min(keep_count * 2, len(preserved)) :]

    def estimate_current_tokens(self) -> int:
        """Estimate total tokens for current conversation state."""
        conv_parts = [m["content"] for m in self._history]
        conv_text = "\n".join(conv_parts)
        return estimate_request_tokens(
            self._system,
            conv_text,
            "",
        ).total

    def _chat(
        self, user_content: str, is_intermediate: bool = False, history_content: str | None = None
    ) -> SupervisorVerdict:
        should_record_user = (
            not is_intermediate
            or not self._compact_intermediate_steps
            or self.should_record_turn(user_content, "user")
        )

        record_content = history_content if history_content is not None else user_content

        conv_parts = []
        for msg in self._history:
            if msg.get("content"):
                conv_parts.append(msg["content"])
        conv_text = "\n".join(conv_parts)

        estimate = estimate_request_tokens(
            self._system,
            conv_text,
            user_content,
        )

        warning_msgs = warn_if_exceeds_limit(estimate, self._max_tokens)
        for msg in warning_msgs:
            self._token_warnings.append(msg)

        if should_truncate(estimate, self._max_tokens):
            logger.warning(
                "--- FULL PROMPT EXCEEDING MAX TOKENS ---\n"
                "SYSTEM:\n%s\n"
                "HISTORY:\n%s\n"
                "USER:\n%s\n"
                "----------------------------------------",
                self._system, conv_text, user_content
            )

        if self._truncation_enabled and should_truncate(estimate, self._max_tokens):
            user_content = truncate_with_fallback(
                user_content,
                self._max_tokens,
                system_prompt=self._system,
                conversation_history=conv_text,
            )
            trunc_warning = (
                f"Prompt truncated to fit within token limit. "
                f"Original: {estimate.total} tokens, Max available: {int(self._max_tokens * (1.0 - 0.25))} tokens"
            )
            logger.warning(trunc_warning)
            self._token_warnings.append(trunc_warning)

        messages = [{"role": "system", "content": self._system}]
        messages.extend(self._history)
        messages.append({"role": "user", "content": user_content})

        response = self._client.chat.completions.create(
            model=self._model,
            messages=messages,
        )
        reply = response.choices[0].message.content or ""
        
        if should_record_user:
            self._history.append({"role": "user", "content": record_content})
        self._history.append({"role": "assistant", "content": reply})

        if len(self._history) > self._max_history_turns * 2:
            if self._compact_intermediate_steps:
                self.compact_history()
            else:
                self._history = self._history[:2] + self._history[4:]

        all_met = any(p in reply.lower() for p in _DONE_PHRASES)
        return SupervisorVerdict(raw=reply, all_targets_met=all_met, feedback=reply)
