"""supervisor/llm_supervisor.py — OpenAI-powered judge."""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from openai import OpenAI

from .protocol import Protocol
from .workspace_guard import _PROTECTED_DIRS, _PROTECTED_FILES
from .token_estimator import (
    estimate_tokens,
    estimate_request_tokens,
    should_warn,
    should_truncate,
    truncate_prompt,
    truncate_with_fallback,
)

logger = logging.getLogger(__name__)

# Markdown files generated by opencode that should be excluded
# when searching for external feedback files.
_OPENCODE_GENERATED_MD: set[str] = {
    "summary.md",
    "failure_report.md",
    "evolution_report.md",
}

_SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__",
              ".checkpoints", ".archive", ".opencode", ".mypy_cache",
              ".pytest_cache", "opencode_supervisor.egg-info"}
_SKIP_DIR_PREFIXES = (".",)


@dataclass
class ProtocolViolation:
    section: str
    description: str
    suggestion: str


@dataclass
class AlignmentResult:
    aligned: bool
    violations: list[ProtocolViolation] = field(default_factory=list)
    reinforcement_message: str = ""


_DONE_PHRASES = [
    "all targets met",
    "all targets are met",
    "targets achieved",
    "task complete",
    "task is complete",
    "objectives met",
    "protocol satisfied",
]


@dataclass
class SupervisorVerdict:
    raw: str
    all_targets_met: bool
    feedback: str


@dataclass
class StepContext:
    current_step: int = 0
    total_steps_estimate: int = 5
    phase: str = "unknown"
    completed_phases: list[str] = field(default_factory=list)


class LLMSupervisor:
    """
    Wraps an OpenAI chat client. Protocol is the system prompt;
    conversation history gives the supervisor persistent memory.
    """

    _MAX_HISTORY_TURNS = 40

    def __init__(
        self,
        protocol: Protocol,
        workspace: Path,
        model: str,
        extra_system: str = "",
        read_external_feedback: bool = False,
        max_tokens: int = 128_000,
    ):
        self._client = OpenAI()
        self._model = model
        self._workspace = workspace
        self._system = protocol.as_system_prompt(workspace) + extra_system
        self._history: list[dict] = []
        self._read_external_feedback = read_external_feedback
        self._max_tokens = max_tokens
        self._token_warnings: list[str] = []

    def read_protected_files(self) -> dict[str, str]:
        """Read all protected files and return their content as a dict mapping path to content."""
        protected_contents: dict[str, str] = {}
        workspace = self._workspace.resolve()

        # Read .opencoderc if it exists at workspace root
        opencoderc = workspace / ".opencoderc"
        if opencoderc.is_file():
            try:
                rel = opencoderc.relative_to(workspace)
                protected_contents[str(rel)] = opencoderc.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                pass

        # Read .opencode file if it exists at workspace root (as a file)
        opencode_file = workspace / ".opencode"
        if opencode_file.is_file():
            try:
                rel = opencode_file.relative_to(workspace)
                protected_contents[str(rel)] = opencode_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                pass

        # Read all files in .opencode/ directory
        opencode_dir = workspace / ".opencode"
        if opencode_dir.is_dir():
            for dirpath, _dirnames, filenames in os.walk(opencode_dir):
                for fname in filenames:
                    fpath = Path(dirpath) / fname
                    try:
                        rel = fpath.relative_to(workspace)
                        protected_contents[str(rel)] = fpath.read_text(encoding="utf-8")
                    except (OSError, UnicodeDecodeError):
                        pass

        return protected_contents

    def _find_feedback_file(self) -> Path | None:
        """Find the latest modified markdown file not generated by opencode.
        
        Falls back to the latest modified file (any extension) if no such
        markdown file exists in the workspace.
        """
        workspace = self._workspace.resolve()
        if not workspace.is_dir():
            return None

        latest_md: Path | None = None
        latest_md_mtime: float = -1.0
        latest_any: Path | None = None
        latest_any_mtime: float = -1.0

        for dirpath, dirnames, filenames in os.walk(workspace):
            dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS and not any(d.startswith(p) for p in _SKIP_DIR_PREFIXES)]
            for fname in filenames:
                fpath = Path(dirpath) / fname
                try:
                    mtime = fpath.stat().st_mtime
                except OSError:
                    continue

                if mtime > latest_any_mtime:
                    latest_any_mtime = mtime
                    latest_any = fpath

                if fpath.suffix.lower() == ".md" and fname not in _OPENCODE_GENERATED_MD:
                    if mtime > latest_md_mtime:
                        latest_md_mtime = mtime
                        latest_md = fpath

        if latest_md is not None:
            logger.info("Using external feedback file: %s", latest_md.relative_to(workspace))
            return latest_md

        if latest_any is not None:
            logger.info(
                "No non-generated .md found; falling back to latest file: %s",
                latest_any.relative_to(workspace),
            )
            return latest_any

        return None

    def _read_feedback_content(self, feedback_file: Path) -> str:
        """Read the content of a feedback file, returning empty string on failure."""
        try:
            content = feedback_file.read_text(encoding="utf-8")
            logger.info(
                "Read %d chars from feedback file: %s",
                len(content),
                feedback_file.relative_to(self._workspace.resolve()),
            )
            return content
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("Failed to read feedback file %s: %s", feedback_file, exc)
            return ""

    def judge(self, opencode_output: str) -> SupervisorVerdict:
        protected_files = self.read_protected_files()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        feedback_context = ""
        if self._read_external_feedback:
            feedback_file = self._find_feedback_file()
            if feedback_file is not None:
                fb_content = self._read_feedback_content(feedback_file)
                if fb_content:
                    feedback_context = (
                        f"\n\n## External Feedback (from {feedback_file.name})\n"
                        f"{fb_content}\n"
                        "Use this external feedback as the primary evaluation input.\n\n"
                    )

        msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            f"{feedback_context}"
            f"{protected_context}"
            f"--- opencode output ---\n{opencode_output}\n--- end ---"
        )
        return self._chat(msg)

    def judge_with_step_context(
        self, opencode_output: str, step_context: StepContext
    ) -> SupervisorVerdict:
        protected_files = self.read_protected_files()
        protected_context = ""
        if protected_files:
            sections = []
            for path, content in protected_files.items():
                sections.append(f"--- {path} ---\n{content}\n--- end {path} ---")
            protected_context = (
                "\n\n## Current Protected Files State\n"
                + "\n\n".join(sections)
                + "\n\n"
            )

        feedback_context = ""
        if self._read_external_feedback:
            feedback_file = self._find_feedback_file()
            if feedback_file is not None:
                fb_content = self._read_feedback_content(feedback_file)
                if fb_content:
                    feedback_context = (
                        f"\n\n## External Feedback (from {feedback_file.name})\n"
                        f"{fb_content}\n"
                        "Use this external feedback as the primary evaluation input.\n\n"
                    )

        phases_str = ", ".join(step_context.completed_phases) if step_context.completed_phases else "none"
        msg = (
            "opencode just produced the following output. "
            "Evaluate it against the protocol.\n"
            "If ALL targets are met say 'all targets met'.\n"
            "Otherwise give clear, actionable feedback.\n\n"
            "--- Step Context ---\n"
            f"Current step: {step_context.current_step}/{step_context.total_steps_estimate}\n"
            f"Current phase: {step_context.phase}\n"
            f"Completed phases: {phases_str}\n\n"
            f"{feedback_context}"
            f"{protected_context}"
            "--- opencode output ---\n"
            f"{opencode_output}\n--- end ---\n\n"
            "Focus your feedback on the current phase and remaining work."
        )
        return self._chat(msg)

    def ask_for_compaction_instructions(self) -> SupervisorVerdict:
        msg = (
            "The opencode agent's context window is nearly full. "
            "Generate instructions for it to:\n"
            "1. Keep only the latest version of every file.\n"
            "2. Retain any foundational/fallback code it may reference.\n"
            "3. Write summary.md to the workspace with: current status, "
            "key decisions, remaining tasks and future directions.\n"
            "Output ONLY the instruction text to send to opencode."
        )
        return self._chat(msg)

    def ask_for_deletion_permission(
        self, candidates: list[str], workspace: Path
    ) -> SupervisorVerdict:
        if not candidates:
            msg = (
                "The opencode agent's context window is nearly full. "
                "Generate instructions for it to:\n"
                "1. Keep only the latest version of every file.\n"
                "2. Retain any foundational/fallback code it may reference.\n"
                "3. Write summary.md to the workspace with: current status, "
                "key decisions, remaining tasks and future directions.\n"
                "Output ONLY the instruction text to send to opencode."
            )
            return self._chat(msg)

        file_list = "\n".join(f"  - {f}" for f in candidates)
        msg = (
            "The opencode agent's context window is nearly full. "
            "Before compacting the context, you MUST address the following cleanup:\n\n"
            "## DELETION PERMISSION\n\n"
            "The supervisor has identified the following files as outdated, unused, or safe to delete:\n\n"
            f"{file_list}\n\n"
            "You are granted permission to DELETE these files ONLY if:\n"
            "1. The file is confirmed outdated (e.g., backup files, old versions, temp files)\n"
            "2. The file is unused by any current code\n"
            "3. The file is not a core module or essential configuration\n\n"
            "Generate instructions for the agent to:\n"
            "1. Review the file list above and DELETE only the confirmed outdated/unused files\n"
            "2. Keep all core modules and essential files\n"
            "3. Keep only the latest version of every file\n"
            "4. Retain any foundational/fallback code it may reference\n"
            "5. Write summary.md to the workspace with: current status, "
            "key decisions, remaining tasks and future directions\n\n"
            "Output ONLY the instruction text to send to opencode, "
            "including explicit permission to delete the listed files."
        )
        return self._chat(msg)

    def report_final_status(
        self, reason: str, opencode_output: str, workspace: Path
    ) -> str:
        msg = (
            f"Run ending. Reason: {reason}\n\n"
            "Write a final report:\n"
            "1. What has been completed.\n"
            "2. Last known bug / blocker.\n"
            "3. Remaining undone tasks.\n\n"
            f"Latest opencode output:\n{opencode_output}"
        )
        return self._chat(msg).raw

    def generate_suggestions(
        self,
        opencode_output: str,
        current_summary: str = "",
        step_context: StepContext | None = None,
    ) -> str:
        context_info = ""
        if step_context:
            phases_str = ", ".join(step_context.completed_phases) if step_context.completed_phases else "none"
            context_info = (
                f"Current step: {step_context.current_step}/{step_context.total_steps_estimate}\n"
                f"Current phase: {step_context.phase}\n"
                f"Completed phases: {phases_str}\n\n"
            )

        summary_context = (
            f"\n\nCurrent implementation summary:\n{current_summary}"
            if current_summary
            else ""
        )

        msg = (
            "Based on the opencode output below and the current implementation status,\n"
            "generate actionable suggestions for improving the code or approach.\n"
            "Focus on:\n"
            "1. Code quality improvements\n"
            "2. Potential bugs or edge cases\n"
            "3. Performance optimizations\n"
            "4. Better patterns or practices\n"
            "5. Missing tests or error handling\n\n"
            f"--- Step Context ---\n{context_info}"
            f"--- opencode output ---\n{opencode_output}\n--- end ---{summary_context}\n\n"
            "Output ONLY the suggestions in a clear, actionable format. "
            "If no suggestions are needed, output 'No suggestions at this time.'"
        )
        return self._chat(msg).raw

    def verify_protocol_alignment(
        self,
        opencode_output: str,
        protocol: Protocol,
    ) -> AlignmentResult:
        violations: list[ProtocolViolation] = []
        output_lower = opencode_output.lower()

        restriction_patterns = [
            (
                r"(do not delete|don't delete|never delete|avoid deleting)",
                "Attempting to delete code without permission",
                "Do not delete files unless explicitly instructed in the TARGET section.",
            ),
            (
                r"(rm\s+-rf|del\s+/[sqf]|\$\(\{|sudo\s+)",
                "Suspicious destructive command detected",
                "Destructive commands require explicit permission. Only proceed if the TARGET explicitly requires it.",
            ),
            (
                r"(\.\.\/|\.\.\\|\.\.\%|\.\.\.)",
                "Path traversal attempt detected",
                "All file operations must stay within the workspace directory. Do not access parent directories.",
            ),
            (
                r"(git\s+reset|git\s+rebase|git\s+push\s+--force|git\s+push\s+-f)",
                "Destructive git operation detected",
                "Do not perform destructive git operations (reset, rebase, force push) without explicit permission.",
            ),
            (
                r"(chmod\s+777|chmod\s+000|\$\(whoami\)|eval\s+\$\{)",
                "Risky shell operation detected",
                "Avoid risky operations involving permissions, command substitution in eval, or dynamic code execution.",
            ),
        ]

        for pattern, description, suggestion in restriction_patterns:
            if re.search(pattern, output_lower):
                violations.append(
                    ProtocolViolation(
                        section="RESTRICTIONS",
                        description=description,
                        suggestion=suggestion,
                    )
                )

        if protocol.target_section:
            target_keywords = self._extract_keywords(protocol.target_section)
            found_keywords = sum(
                1 for kw in target_keywords if kw.lower() in output_lower
            )
            if target_keywords and found_keywords == 0:
                violations.append(
                    ProtocolViolation(
                        section="TARGET",
                        description="No evidence of target-related activity in output",
                        suggestion=f"Your output should address these target keywords: {', '.join(target_keywords[:5])}",
                    )
                )

        if protocol.restrictions_section:
            restriction_keywords = self._extract_keywords(protocol.restrictions_section)
            for kw in restriction_keywords:
                if kw.lower() in output_lower and any(
                    word in output_lower
                    for word in ["ignore", "skip", "bypass", "violate"]
                ):
                    violations.append(
                        ProtocolViolation(
                            section="RESTRICTIONS",
                            description=f"Potential attempt to ignore restriction keyword: {kw}",
                            suggestion="You must comply with all restrictions listed in the protocol.",
                        )
                    )
                    break

        aligned = len(violations) == 0
        reinforcement_message = (
            self._generate_reinforcement_message(violations) if violations else ""
        )

        return AlignmentResult(
            aligned=aligned,
            violations=violations,
            reinforcement_message=reinforcement_message,
        )

    def _extract_keywords(self, text: str) -> list[str]:
        words = re.findall(r"\b[a-zA-Z]{4,}\b", text)
        stopwords = {
            "that",
            "this",
            "with",
            "from",
            "have",
            "will",
            "been",
            "were",
            "they",
            "their",
            "what",
            "when",
            "your",
            "must",
            "only",
            "also",
            "into",
            "than",
            "then",
            "should",
            "could",
            "would",
            "which",
            "about",
            "after",
            "before",
            "being",
        }
        return [w for w in words if w.lower() not in stopwords][:10]

    def _generate_reinforcement_message(
        self, violations: list[ProtocolViolation]
    ) -> str:
        if not violations:
            return ""

        lines = [
            "\n--- PROTOCOL VIOLATION DETECTED ---\n",
            "The following protocol violations were detected in your output:\n",
        ]

        for i, v in enumerate(violations, 1):
            lines.append(f"{i}. [{v.section}] {v.description}")
            lines.append(f"   Correction: {v.suggestion}\n")

        lines.extend(
            [
                "Please review the protocol sections above and correct your approach.\n",
                "Reminder:\n",
                "  - INPUT section describes the task context you must understand\n",
                "  - TARGET section lists the objectives you must achieve\n",
                "  - RESTRICTIONS section defines boundaries you must not cross\n",
                "Re-read these sections and adjust your actions accordingly.\n",
                "--- END VIOLATION NOTICE ---\n",
            ]
        )

        return "".join(lines)

    # ------------------------------------------------------------------ #

    def get_token_warnings(self) -> list[str]:
        """Return collected token warning messages."""
        return list(self._token_warnings)

    def clear_token_warnings(self) -> None:
        """Clear token warning messages."""
        self._token_warnings.clear()

    def estimate_current_tokens(self) -> int:
        """Estimate total tokens for current conversation state."""
        conv_parts = [m["content"] for m in self._history]
        conv_text = "\n".join(conv_parts)
        return estimate_request_tokens(
            self._system,
            conv_text,
            "",
        ).total

    def _chat(self, user_content: str) -> SupervisorVerdict:
        self._history.append({"role": "user", "content": user_content})

        if len(self._history) > self._MAX_HISTORY_TURNS * 2:
            self._history = self._history[:2] + self._history[4:]

        # Build conversation text for token estimation
        conv_parts = []
        for msg in self._history:
            if msg.get("content"):
                conv_parts.append(msg["content"])
        conv_text = "\n".join(conv_parts)

        # Estimate tokens
        estimate = estimate_request_tokens(
            self._system,
            conv_text,
            user_content,
        )

        # Warn if approaching limit
        if should_warn(estimate, self._max_tokens):
            warning_msg = (
                f"Estimated request tokens ({estimate.total}) approaching model maximum "
                f"({self._max_tokens}). System: {estimate.system_prompt}, "
                f"History: {estimate.conversation_history}, Input: {estimate.user_input}."
            )
            logger.warning(warning_msg)
            self._token_warnings.append(warning_msg)

        # Truncate user content if needed
        if should_truncate(estimate, self._max_tokens):
            user_content = truncate_with_fallback(
                user_content,
                self._max_tokens,
                system_prompt=self._system,
                conversation_history=conv_text,
            )
            # Update the last history entry
            self._history[-1]["content"] = user_content

        response = self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": self._system},
                *self._history,
            ],
        )
        reply = response.choices[0].message.content or ""
        self._history.append({"role": "assistant", "content": reply})

        all_met = any(p in reply.lower() for p in _DONE_PHRASES)
        return SupervisorVerdict(raw=reply, all_targets_met=all_met, feedback=reply)
